name: Build/release

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - run: electron-forge package
        
      - name: Upload release
        uses: yakuhzi/action-release@v1
        with:
          changelog: ./out/CHANGELOG.txt
          file: ./out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
